name: drz-metrics
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.1.0
  - absl-py=0.7.1
  - astor=0.7.1
  - blas=1.0
  - c-ares=1.15.0
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - cudatoolkit=10.0.130
  - cudnn=7.3.1
  - cupti=10.0.130
  - freetype=2.9.1
  - gast=0.2.2
  - grpcio=1.16.1
  - h5py=2.9.0
  - hdf5=1.10.4
  - intel-openmp=2019.3
  - jpeg=9b
  - keras=2.2.4
  - keras-applications=1.0.7
  - keras-base=2.2.4
  - keras-preprocessing=1.0.9
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.7.1
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.10
  - markdown=3.1
  - mkl=2019.3
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - mock=2.0.0
  - ncurses=6.1
  - numpy=1.16.3
  - numpy-base=1.16.3
  - olefile=0.46
  - openssl=1.1.1b
  - pbr=5.1.3
  - pillow=6.0.0
  - pip=19.1.1
  - protobuf=3.7.1
  - python=3.7.3
  - pyyaml=5.1
  - readline=7.0
  - scipy=1.2.1
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.28.0
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - termcolor=1.1.0
  - tk=8.6.8
  - werkzeug=0.15.2
  - wheel=0.33.4
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - ansimarkup==1.4.0
    - attrs==19.1.0
    - backcall==0.1.0
    - better-exceptions-fork==0.2.1.post6
    - biwrap==0.1.6
    - bleach==3.1.0
    - bokeh==1.2.0
    - cachetools==3.1.1
    - chardet==3.0.4
    - colorama==0.4.1
    - cycler==0.10.0
    - decorator==4.4.0
    - defusedxml==0.6.0
    - dill==0.2.9
    - entrypoints==0.3
    - ffmpeg==1.4
    - future==0.17.1
    - google-api-python-client==1.7.11
    - google-auth==1.6.3
    - google-auth-httplib2==0.0.3
    - google-auth-oauthlib==0.4.0
    - google-pasta==0.1.7
    - googleapis-common-protos==1.6.0
    - holoviews==1.12.3
    - httplib2==0.13.1
    - idna==2.8
    - imageio==2.5.0
    - ipykernel==5.1.1
    - ipython==7.6.0
    - ipython-genutils==0.2.0
    - jedi==0.14.0
    - jinja2==2.10.1
    - joblib==0.13.2
    - jsonschema==3.0.1
    - jupyter-client==5.2.4
    - jupyter-core==4.5.0
    - kiwisolver==1.1.0
    - loguru==0.2.5
    - markupsafe==1.1.1
    - matplotlib==3.1.0
    - mistune==0.8.4
    - nbconvert==5.5.0
    - nbformat==4.4.0
    - networkx==2.3
    - notebook==5.7.8
    - oauthlib==3.1.0
    - opencv-python==4.1.1.26
    - packaging==19.0
    - pandas==0.24.2
    - pandocfilters==1.4.2
    - panel==0.6.0
    - param==1.9.1
    - parso==0.5.0
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - progress==1.5
    - prometheus-client==0.7.1
    - promise==2.2.1
    - prompt-toolkit==2.0.9
    - psutil==5.6.2
    - ptyprocess==0.6.0
    - pyasn1==0.4.7
    - pyasn1-modules==0.2.6
    - pyct==0.4.6
    - pygments==2.4.0
    - pyparsing==2.4.0
    - pyrsistent==0.15.2
    - python-dateutil==2.8.0
    - pytz==2019.1
    - pyviz-comms==0.7.2
    - pywavelets==1.0.3
    - pyzmq==18.0.2
    - requests==2.22.0
    - requests-oauthlib==1.2.0
    - rsa==4.0
    - scikit-image==0.15.0
    - scikit-learn==0.21.1
    - seaborn==0.9.0
    - send2trash==1.5.0
    - sewar==0.4.2
    - tensorflow-datasets==1.0.2
    - tensorflow-gpu==1.13.1
    - tensorflow-metadata==0.13.0
    - tensorflow-plot==0.3.2
    - terminado==0.8.2
    - testpath==0.4.2
    - tornado==6.0.3
    - tqdm==4.32.1
    - traitlets==4.3.2
    - uritemplate==3.0.0
    - urllib3==1.25.2
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - wrapt==1.11.1

