channels:
- conda-forge
- defaults
dependencies:
- flake8
- codespell
- matplotlib
- numpydoc
- pillow
- pip
- pydocstyle
- pytest
- pytest-cov
- pytest-mock
- pytest-timeout
- sphinx
- sphinx_rtd_theme
- pip:
  - pytest-sugar
  - sphinx-gallery



